import pygame as pg

# MISC
SCREENSIZE = SCREENWIDE, SCREENHIGH = (400,400)
BACKGROUNDCOLOR = "dark gray"
FRAMERATE = 30

# BALL
BALLSPEED = BALLSPX, BALLSPY = (10,10)
BALLDIAM = 6
BALLCOLOR = "black"

