import pygame as pg

# MISC
SCREENSIZE = SCREENWIDTH, SCREENHEIGHT = (400,400)
BACKGROUNDCOLOR = "dark gray"
FRAMERATE = 30

# PADDLE
PADDLESPEED = PADDLESPX, PADDLESPY = (0,12)
PADDLETHICK = 12
PADDLELENGTH = 80
PADDLEOFFSET = 10
PADDLECOLORLEFT = "red"
PADDLECOLORRIGHT = "blue"
